import { z } from "zod"

/**
 * A simplified descriptor for one param field of a source's params_schema.
 * Generated by `serialize_params_schema` server-side and delivered via the API
 * so that universal page loads can render source-specific param forms without
 * importing any server-only code.
 *
 * This is the canonical definition. `$lib/components/SubscriptionForm.types`
 * re-exports the type alias from here to avoid drift.
 */
export const ParamDescriptorSchema = z.object({
	key: z.string(),
	type: z.enum(["string", "number", "boolean", "enum", "array_string"]),
	enum_values: z.array(z.string()).optional(),
	default: z.unknown().optional(),
	optional: z.boolean().optional(),
	label: z.string().optional(),
})

export type ParamDescriptor = z.infer<typeof ParamDescriptorSchema>

export const SourceListItemSchema = z.object({
	slug: z.string(),
	display_name: z.string(),
	param_descriptors: z.array(ParamDescriptorSchema),
})

export type SourceListItem = z.infer<typeof SourceListItemSchema>

export const ListSourcesResponseSchema = z.object({
	items: z.array(SourceListItemSchema),
})

export type ListSourcesResponse = z.infer<typeof ListSourcesResponseSchema>
