/**
 * Shared types for SubscriptionForm. Extracted to a plain .ts file so that
 * plain `tsc --noEmit` (the lefthook gate) can see them without the Svelte
 * compiler plugin.
 */

/**
 * A simplified descriptor for one param field of a source's params_schema.
 * Generated by `serialize_params_schema` server-side and passed to the client
 * for rendering a dynamic form section.
 */
export interface ParamDescriptor {
	key: string
	type: "string" | "number" | "boolean" | "enum" | "array_string"
	enum_values?: string[]
	default?: unknown
	optional?: boolean
	label?: string
}
